import { z } from "zod";
// RemovalReason is generated by `prisma generate` from the schema enum.

/** Typed shape of CommitteeMembership.submissionMetadata (leader request context). */
export type CommitteeMembershipSubmissionMetadata = {
  removeMemberId?: string;
  requestNotes?: string;
};

/** Response shape from /api/fetchCommitteeList with memberships + voterRecord + seats + maxSeatsPerLted. */
export type FetchCommitteeListResponse = CommitteeList & {
  ltedWeight?: number | string | null;
  memberships: Array<{
    voterRecord: VoterRecord;
    membershipType: MembershipType | null;
    seatNumber?: number | null;
  }>;
  seats?: Array<{
    id: string;
    seatNumber: number;
    isPetitioned: boolean;
    weight: number | string | null;
  }>;
  maxSeatsPerLted?: number;
};
// TS error below resolves after running `prisma migrate dev` or `prisma generate`.
import {
  type CommitteeList,
  type VoterRecord,
  MembershipType,
  RemovalReason,
} from "@prisma/client";

// Committee data validation schema
export const committeeDataSchema = z
  .object({
    cityTown: z.string().trim().min(1, "City/Town is required"),
    legDistrict: z
      .union([z.string(), z.number()])
      .optional()
      .refine(
        (val) =>
          val === undefined ||
          (typeof val === "string" ? val.trim() !== "" : true),
        {
          message: "Legislative District cannot be empty when provided",
        },
      )
      .transform((val) => {
        if (val === undefined) return undefined;
        if (typeof val === "string") return val.trim();
        return val.toString();
      })
      .pipe(
        z.coerce
          .number()
          .int()
          .optional()
          .refine((val) => val === undefined || val > 0, {
            message:
              "Legislative District must be a positive integer when provided",
          }),
      ),
    electionDistrict: z.coerce
      .number()
      .int()
      .positive("Election District must be a positive integer"),
    memberId: z.string().trim().min(1, "Member ID is required"),
    membershipType: z.nativeEnum(MembershipType).optional(),
  })
  .strict();

// Committee request data validation schema
export const committeeRequestDataSchema = z
  .object({
    cityTown: z.string().trim().min(1, "City/Town is required"),
    legDistrict: z.coerce
      .number()
      .int()
      .optional()
      .refine((val) => val === undefined || val > 0, {
        message:
          "Legislative District must be a positive integer when provided",
      }),
    electionDistrict: z.coerce
      .number()
      .int()
      .positive("Election District must be a positive integer"),
    addMemberId: z
      .string()
      .trim()
      .nullable()
      .optional()
      .transform((v) => (v == null || v === "" ? undefined : v)),
    removeMemberId: z
      .string()
      .trim()
      .nullable()
      .optional()
      .transform((v) => (v == null || v === "" ? undefined : v)),
    requestNotes: z
      .string()
      .trim()
      .max(1000, "Notes must be 1000 characters or fewer")
      .optional(),
  })
  .strict()
  .refine(
    (data) => {
      const hasAddMember = data.addMemberId && data.addMemberId.trim() !== "";
      const hasRemoveMember =
        data.removeMemberId && data.removeMemberId.trim() !== "";
      return Boolean(hasAddMember) || Boolean(hasRemoveMember);
    },
    {
      message:
        "At least one action is required: either addMemberId or removeMemberId must be provided",
    },
  )
  .refine(
    (data) => Boolean(data.addMemberId?.trim()),
    {
      message:
        "addMemberId is required; remove-only requests should contact an administrator",
    },
  );

// Remove committee member validation schema (extends committeeDataSchema with optional reason)
export const removeCommitteeDataSchema = z
  .object({
    cityTown: z.string().trim().min(1, "City/Town is required"),
    legDistrict: z
      .union([z.string(), z.number()])
      .optional()
      .refine(
        (val) =>
          val === undefined ||
          (typeof val === "string" ? val.trim() !== "" : true),
        { message: "Legislative District cannot be empty when provided" },
      )
      .transform((val) => {
        if (val === undefined) return undefined;
        if (typeof val === "string") return val.trim();
        return val.toString();
      })
      .pipe(
        z.coerce
          .number()
          .int()
          .optional()
          .refine((val) => val === undefined || val > 0, {
            message:
              "Legislative District must be a positive integer when provided",
          }),
      ),
    electionDistrict: z.coerce
      .number()
      .int()
      .positive("Election District must be a positive integer"),
    memberId: z.string().trim().min(1, "Member ID is required"),
    removalReason: z.nativeEnum(RemovalReason).optional(),
    removalNotes: z.string().trim().max(1000).optional(),
  })
  .strict();

// Handle committee membership request data validation schema (SRS 1.2 — uses CommitteeMembership)
export const handleCommitteeRequestDataSchema = z
  .object({
    membershipId: z.string().min(1, "Membership ID is required"),
    acceptOrReject: z.enum(["accept", "reject"], {
      errorMap: () => ({
        message: "Accept or reject must be either 'accept' or 'reject'",
      }),
    }),
  })
  .strict();

// Update LTED weight (SRS 1.4)
export const updateLtedWeightSchema = z
  .object({
    committeeListId: z.coerce.number().int().positive(),
    ltedWeight: z
      .number()
      .nonnegative("LTED weight must be non-negative")
      .nullable(),
  })
  .strict();

// Fetch committee list query parameters validation schema
export const fetchCommitteeListQuerySchema = z
  .object({
    cityTown: z.string().trim().min(1, "City/Town is required"),
    legDistrict: z
      .string()
      .trim()
      .transform((v) => (v === "" ? undefined : v))
      .optional()
      .refine(
        (val) => {
          if (val === undefined) return true;
          const parsed = Number(val);
          return Number.isInteger(parsed) && parsed > 0;
        },
        {
          message:
            "Legislative District must be a positive integer when provided",
        },
      ),
    electionDistrict: z
      .string()
      .trim()
      .regex(/^\d+$/, "Election District must contain only digits"),
  })
  .strict();

// API Response types for committee operations
export type AddCommitteeResponse =
  | {
      success: true;
      message: string;
      idempotent?: true;
    }
  | { success: false; error: string };

export type CommitteeRequestResponse =
  | {
      success: true;
      message: string;
    }
  | { success: false; error: string };

// Type exports derived from schemas
export type CommitteeData = z.infer<typeof committeeDataSchema>;
export type RemoveCommitteeData = z.infer<typeof removeCommitteeDataSchema>;
export type CommitteeRequestData = z.infer<typeof committeeRequestDataSchema>;
export type HandleCommitteeRequestData = z.infer<
  typeof handleCommitteeRequestDataSchema
>;
export type FetchCommitteeListQuery = z.infer<
  typeof fetchCommitteeListQuerySchema
>;
